### ISSUE TITLE
`annotation-no-unknown` should allow `!default`

### ISSUE THREAD

**Issue by Hyzual** [stylelint-scss/stylelint-config-recommended-scss#131]
Hi, thank you for maintaining this stylelint configuration, it is very helpful 👍.

Since v14.10.0, stylelint added the [annotation-no-unknown](https://stylelint.io/user-guide/rules/list/annotation-no-unknown) rule. Given that `!default` is a [valid flag][0] for Sass variables, I suggest to add some configuration to allow it. This way, users of this config will not have errors raised on their default Sass variables.

Before the change:
```scss
$my-variable: #ff0000 !default; // ✖  Unexpected unknown annotation "!default"  annotation-no-unknown
```

After the change:
```scss
$my-variable: #ff0000 !default; // No error
```

What do you think about it ? I'll submit a PR for it shortly.

[0]:https://sass-lang.com/documentation/variables#default-values

**Comment by jnoordsij** [comment]
This could be combined with https://github.com/stylelint-scss/stylelint-config-recommended-scss/pull/117, because the rule is enabled in [`stylelint-config-recommended` version 9.0](https://github.com/stylelint/stylelint-config-recommended/blob/main/CHANGELOG.md), which causes this error to appear now for users.

**Comment by kristerkari** [comment]
Thanks, sure, let's fix this!
